### ISSUE TITLE
variable inconsistency between config_manager and cisco_ios

### ISSUE THREAD

**Issue by IPvSean** [ansible-network/config_manager#17]
In the dos for config_manager->
```
    - name: get active configuration from device
      include_role:
        name: ansible-network.config_manager
        tasks_from: get

    - name: display the device configuration to stdout
      debug:
        var: config_manager.config.split('\n')
```

but in the cisco_ios role the actual task is registering to `configuration`->
```
- name: run command and return configuration
  cli:
    command: "{{ ios_config_source[source | default('running')] }}"
  register: configuration
```
